In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("loan_data.csv")

df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1


In [3]:
X = df.drop("loan_status", axis=1)
y = df["loan_status"]

print(X.shape)
print(y.shape)

(45000, 13)
(45000,)


In [4]:
from sklearn.model_selection import train_test_split

# split data: 80% training, 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train.shape)
print(X_test.shape)

(36000, 13)
(9000, 13)


In [6]:
# convert categorical text variables to numbers
X_train = pd.get_dummies(X_train)
X_test = pd.get_dummies(X_test)

# make sure both datasets have same columns
X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

print(X_train.shape)
print(X_test.shape)

(36000, 27)
(9000, 27)


In [7]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

print("Model training completed")

Model training completed


/usr/local/python/3.12.1/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [8]:
y_pred = model.predict(X_test)

print(y_pred[:10])

[0 0 1 0 1 0 0 1 0 1]


In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)

Confusion Matrix:
[[6488  502]
 [ 541 1469]]
Accuracy: 0.8841111111111111
Precision: 0.7453069507864029
Recall: 0.7308457711442786


In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [11]:
from sklearn.linear_model import LogisticRegression

model_scaled = LogisticRegression(max_iter=2000)

model_scaled.fit(X_train_scaled, y_train)

print("Scaled model training completed")

Scaled model training completed


In [12]:
y_pred_scaled = model_scaled.predict(X_test_scaled)

print(y_pred_scaled[:10])

[0 0 1 0 1 0 0 1 0 1]


In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

cm_scaled = confusion_matrix(y_test, y_pred_scaled)
acc_scaled = accuracy_score(y_test, y_pred_scaled)
prec_scaled = precision_score(y_test, y_pred_scaled)
rec_scaled = recall_score(y_test, y_pred_scaled)

print("Confusion Matrix (Scaled):")
print(cm_scaled)
print("Accuracy:", acc_scaled)
print("Precision:", prec_scaled)
print("Recall:", rec_scaled)

Confusion Matrix (Scaled):
[[6558  432]
 [ 519 1491]]
Accuracy: 0.8943333333333333
Precision: 0.7753510140405616
Recall: 0.7417910447761195


In [14]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_scaled))

              precision    recall  f1-score   support

           0       0.93      0.94      0.93      6990
           1       0.78      0.74      0.76      2010

    accuracy                           0.89      9000
   macro avg       0.85      0.84      0.85      9000
weighted avg       0.89      0.89      0.89      9000

